/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/specialists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Specialists */
        get: operations["list_specialists_api_specialists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match Case
         * @description Parse notes -> guardrail + rank specialists -> look up trials.
         *
         *     Synchronous in the mock. In production this enqueues a Celery job.
         */
        post: operations["match_case_api_cases__case_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Referrals */
        get: operations["list_referrals_api_referrals_get"];
        put?: never;
        /** Create Referral */
        post: operations["create_referral_api_referrals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/referrals/{referral_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Referral Status */
        patch: operations["set_referral_status_api_referrals__referral_id__status_patch"];
        trace?: never;
    };
    "/api/specialists/{specialist_id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Slots */
        get: operations["list_slots_api_specialists__specialist_id__slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book Appointment */
        post: operations["book_appointment_api_appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Consults
         * @description One consult thread per specialist (id == specialist id) in the mock.
         */
        get: operations["list_consults_api_consults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consults/{consult_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_consults__consult_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppointmentCreate */
        AppointmentCreate: {
            /** Referral Id */
            referral_id: string;
            /** Slot Id */
            slot_id: string;
        };
        /** Case */
        Case: {
            /** Title */
            title: string;
            /** Patient Age */
            patient_age: number;
            /**
             * Patient Sex
             * @enum {string}
             */
            patient_sex: "F" | "M" | "X";
            /**
             * Urgency
             * @default routine
             * @enum {string}
             */
            urgency: "routine" | "urgent" | "emergent";
            /**
             * Notes
             * @description Free-text clinical notes
             */
            notes: string;
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /** Referring Physician Id */
            referring_physician_id: string;
        };
        /** CaseCreate */
        CaseCreate: {
            /** Title */
            title: string;
            /** Patient Age */
            patient_age: number;
            /**
             * Patient Sex
             * @enum {string}
             */
            patient_sex: "F" | "M" | "X";
            /**
             * Urgency
             * @default routine
             * @enum {string}
             */
            urgency: "routine" | "urgent" | "emergent";
            /**
             * Notes
             * @description Free-text clinical notes
             */
            notes: string;
        };
        /** Consult */
        Consult: {
            /** Id */
            id: string;
            specialist: components["schemas"]["Specialist"];
            last_message?: components["schemas"]["ConsultMessage"] | null;
        };
        /** ConsultMessage */
        ConsultMessage: {
            /** Id */
            id: string;
            /** Consult Id */
            consult_id: string;
            /** Sender Id */
            sender_id: string;
            /** Sender Name */
            sender_name: string;
            /** Body */
            body: string;
            /** Sent At */
            sent_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatchResult */
        MatchResult: {
            /** Case Id */
            case_id: string;
            parsed: components["schemas"]["ParsedCase"];
            /** Specialists */
            specialists: components["schemas"]["SpecialistMatch"][];
            /** Trials */
            trials: components["schemas"]["Trial"][];
        };
        /**
         * ParsedCase
         * @description What the AI layer extracts from free-text notes.
         */
        ParsedCase: {
            /** Condition */
            condition: string;
            /** Specialty */
            specialty: string;
            /** Keywords */
            keywords: string[];
        };
        /** Referral */
        Referral: {
            /** Case Id */
            case_id: string;
            /** Specialist Id */
            specialist_id: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "accepted" | "declined" | "scheduled";
            /** Created At */
            created_at: string;
            /** Appointment Slot Id */
            appointment_slot_id?: string | null;
        };
        /** ReferralCreate */
        ReferralCreate: {
            /** Case Id */
            case_id: string;
            /** Specialist Id */
            specialist_id: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** Slot */
        Slot: {
            /** Id */
            id: string;
            /** Specialist Id */
            specialist_id: string;
            /** Starts At */
            starts_at: string;
            /**
             * Booked
             * @default false
             */
            booked: boolean;
        };
        /** Specialist */
        Specialist: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Specialty */
            specialty: string;
            /** Subspecialties */
            subspecialties: string[];
            /** Hospital */
            hospital: string;
            /** City */
            city: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Accepting Referrals */
            accepting_referrals: boolean;
        };
        /** SpecialistMatch */
        SpecialistMatch: {
            specialist: components["schemas"]["Specialist"];
            /**
             * Score
             * @description 0-1, higher is a better fit
             */
            score: number;
            /** Distance Km */
            distance_km: number;
            /** Rationale */
            rationale: string;
            next_slot?: components["schemas"]["Slot"] | null;
        };
        /** Trial */
        Trial: {
            /** Nct Id */
            nct_id: string;
            /** Title */
            title: string;
            /** Condition */
            condition: string;
            /** Phase */
            phase: string;
            /** Location */
            location: string;
            /** Url */
            url: string;
        };
        /** User */
        User: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "referring_physician" | "specialist" | "admin";
            /** City */
            city: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    list_specialists_api_specialists_get: {
        parameters: {
            query?: {
                specialty?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Specialist"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"][];
                };
            };
        };
    };
    create_case_api_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_case_api_cases__case_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_referrals_api_referrals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Referral"][];
                };
            };
        };
    };
    create_referral_api_referrals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferralCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Referral"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_referral_status_api_referrals__referral_id__status_patch: {
        parameters: {
            query: {
                status: "pending" | "accepted" | "declined" | "scheduled";
            };
            header?: never;
            path: {
                referral_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Referral"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_slots_api_specialists__specialist_id__slots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_appointment_api_appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Referral"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consults_api_consults_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consult"][];
                };
            };
        };
    };
    list_messages_api_consults__consult_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consult_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsultMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
