"""add trial approval to referrals

Revision ID: 0dd4b3376e3c
Revises: 4710d0b4dbb5
Create Date: 2026-09-19 16:57:24.476993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd4b3376e3c'
down_revision: Union[str, Sequence[str], None] = '4710d0b4dbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('trial_approval', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'trial_approval')
    # ### end Alembic commands ###
