"""add scheduling and insurance network tables

Revision ID: 4710d0b4dbb5
Revises: 8c7b35eaf198
Create Date: 2026-09-19 16:43:55.129033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4710d0b4dbb5'
down_revision: Union[str, Sequence[str], None] = '8c7b35eaf198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', name='uq_appointments_slot_id')
    )
    op.create_index(op.f('ix_appointments_referral_id'), 'appointments', ['referral_id'], unique=False)
    op.create_index(op.f('ix_appointments_slot_id'), 'appointments', ['slot_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('specialist_id', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_specialist_id'), 'slots', ['specialist_id'], unique=False)
    op.create_index(op.f('ix_slots_start'), 'slots', ['start'], unique=False)
    op.create_table('specialist_insurance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('specialist_id', sa.String(), nullable=False),
    sa.Column('payer', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialist_id', 'payer', name='uq_specialist_insurance_specialist_payer')
    )
    op.create_index(op.f('ix_specialist_insurance_payer'), 'specialist_insurance', ['payer'], unique=False)
    op.create_index(op.f('ix_specialist_insurance_specialist_id'), 'specialist_insurance', ['specialist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialist_insurance_specialist_id'), table_name='specialist_insurance')
    op.drop_index(op.f('ix_specialist_insurance_payer'), table_name='specialist_insurance')
    op.drop_table('specialist_insurance')
    op.drop_index(op.f('ix_slots_start'), table_name='slots')
    op.drop_index(op.f('ix_slots_specialist_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_appointments_slot_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_referral_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
