"""initial schema

Revision ID: 8c7b35eaf198
Revises: 
Create Date: 2026-09-19 14:38:23.267535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7b35eaf198'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('weight_profile', sa.String(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('too_late', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_runs_referral_id'), 'match_runs', ['referral_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('payer', sa.String(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physicians',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('practice_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('referring_physician_id', sa.String(), nullable=False),
    sa.Column('case_notes', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('complexity', sa.String(), nullable=True),
    sa.Column('parsed_case', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approval', sa.JSON(), nullable=True),
    sa.Column('appointment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_referrals_referring_physician_id'), 'referrals', ['referring_physician_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('specialists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('subspecialties', sa.JSON(), nullable=False),
    sa.Column('practice_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialists_specialty'), 'specialists', ['specialty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialists_specialty'), table_name='specialists')
    op.drop_table('specialists')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referring_physician_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('physicians')
    op.drop_table('patients')
    op.drop_index(op.f('ix_match_runs_referral_id'), table_name='match_runs')
    op.drop_table('match_runs')
    # ### end Alembic commands ###
