"""add consult threads and messages

Revision ID: d77696b64f84
Revises: 0dd4b3376e3c
Create Date: 2026-09-19 17:10:18.474672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77696b64f84'
down_revision: Union[str, Sequence[str], None] = '0dd4b3376e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consult_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('sender_physician_id', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consult_messages_created_at'), 'consult_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_consult_messages_thread_id'), 'consult_messages', ['thread_id'], unique=False)
    op.create_table('consult_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('initiator_physician_id', sa.String(), nullable=False),
    sa.Column('recipient_physician_id', sa.String(), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consult_threads_initiator_physician_id'), 'consult_threads', ['initiator_physician_id'], unique=False)
    op.create_index(op.f('ix_consult_threads_recipient_physician_id'), 'consult_threads', ['recipient_physician_id'], unique=False)
    op.create_index(op.f('ix_consult_threads_referral_id'), 'consult_threads', ['referral_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consult_threads_referral_id'), table_name='consult_threads')
    op.drop_index(op.f('ix_consult_threads_recipient_physician_id'), table_name='consult_threads')
    op.drop_index(op.f('ix_consult_threads_initiator_physician_id'), table_name='consult_threads')
    op.drop_table('consult_threads')
    op.drop_index(op.f('ix_consult_messages_thread_id'), table_name='consult_messages')
    op.drop_index(op.f('ix_consult_messages_created_at'), table_name='consult_messages')
    op.drop_table('consult_messages')
    # ### end Alembic commands ###
